# Generated by Django 3.2.6 on 2021-08-14 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_post_word'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='word',
        ),
    ]
